
from Classes.PDF_Extractor import Extractor
from Classes.OllamaAI import AI


###############
#Variables
###############


#TODO: Have this generated by AI
unwanted = [
    "Discount Mufflers",
    "Prepared by AI on 05/14/2024", 
    "Customer List",
]


#############
#Objects
#############


extractor = Extractor(
    target_document="Source-Documents/DiscountMufflers1.pdf",
    unwanted_text=unwanted,
    delimiter=" ",
    )

ai = AI(
    server_ip="192.168.1.90:11434",
    data_form_factor="[First and Last Name], [Street Address + Suite/Apartment if available], [City State Abbreviation and Zip-Code].",
    validating_modifier="Remove the comma located between the city and state if present."
    )


#############
#Main Body
#############


extractor.extract_text()

# for line in extractor.lines:
#     ai.arrange_line(line)
    
